---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python and dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - postgresql
      - postgresql-contrib
      - libpq-dev
    state: present

- name: Create application directory
  file:
    path: /var/www/contact-management
    state: directory
    mode: '0755'

- name: Clone repository
  git:
    repo: "https://github.com/YourUsername/contact-management.git"
    dest: /var/www/contact-management
    version: main

- name: Create virtual environment
  command:
    cmd: python3 -m venv venv
    chdir: /var/www/contact-management/backend
    creates: /var/www/contact-management/backend/venv

- name: Install Python requirements
  pip:
    requirements: /var/www/contact-management/backend/requirements.txt
    virtualenv: /var/www/contact-management/backend/venv

- name: Run Django migrations
  shell: |
    source venv/bin/activate
    python manage.py migrate
  args:
    chdir: /var/www/contact-management/backend

- name: Setup Gunicorn
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  notify: restart gunicorn
