version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd frontend
      - npm install
  
  build:
    commands:
      - npm run build
      
  post_build:
    commands:
      - aws s3 sync build/ s3://your-bucket-name --delete
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build'