version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build
      
  post_build:
    commands:
      - aws s3 sync build/ s3://contact-management-frontend-851725490917 --delete

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build'