# Generated by Django 5.1.2 on 2024-10-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20241025_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
