---
- name: Configure common settings
  hosts: all
  become: yes
  roles:
    - common

- name: Configure frontend
  hosts: frontendservers
  become: yes
  roles:
    - frontend

- name: Configure backend
  hosts: backendservers
  become: yes
  roles:
    - backend
