name: Deploy to AWS

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Setup Python for Backend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Setup Node.js for Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Backend Deploy
    - name: Install Python dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage

    - name: Run backend tests
      working-directory: ./backend
      run: |
        python manage.py test

    # Frontend Deploy
    - name: Install Node dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build React app
      working-directory: ./frontend
      run: npm run build

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or your preferred region

    # Deploy Frontend to S3
    - name: Deploy frontend to S3
      working-directory: ./frontend
      run: |
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

    # Deploy Backend to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/contact-app
          git pull
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
